version: '3.8'

services:
    backend:
        build: ./backend
        image: api
        restart: unless-stopped
        volumes:
            - ./backend:/app
        depends_on:
            - mongodb
        ports:
            - '8000:8000'

    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: unless-stopped
        volumes:
            # - ./mongodb/initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - mongodb-data:/data/db/
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - 27017:27017

    mongo-express:
        image: mongo-express:latest
        container_name: mongo-express
        restart: always
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_MONGODB_PORT: 27017
            # ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_URL: mongodb://root:password@mongodb:27017/
            ME_CONFIG_BASICAUTH_USERNAME: user
            ME_CONFIG_BASICAUTH_PASSWORD: password
        ports:
            - 8081:8081
        depends_on:
            - mongodb

volumes:
    mongodb-data:
        driver: local
        name: mongo-data
